[package]
name = "imagecolorizer"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.21", features = ["derive", "wrap_help"] }
image = "0.25.0"
memoize = "0.4.2"
quantette = "0.3.0"
rayon = "1.10.0"

[profile.release]
opt-level = 3
